# Generated by Django 2.2 on 2019-04-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20190414_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='image_url',
            field=models.URLField(default='http://skandalno.net/wp-content/uploads/2014/02/Boiko-Borisov-1.jpg'),
        ),
    ]
